// Stub for source react-app's generatePdf.js — full port pending.
// Source: inventor-studio-react-app/src/utils/generatePdf.js (~1k lines, jsPDF-based).
//
// Until ported, this just opens a print preview of the structured data so
// users can save-as-PDF via the browser. Functional fallback, ugly output.

interface InventionPdfArgs {
  invention: {
    title?: string
    domain?: string
    seed_concept?: string
    created_at?: string
  }
  agents: Record<string, string>
  synthesis: any
  critique: any
  mvpSpec: any
  seedConcept: string
  enrichedGuide?: any
}

export async function generateInventionPdf(args: InventionPdfArgs): Promise<void> {
  const { invention, agents, synthesis, critique, mvpSpec } = args
  const w = window.open('', '_blank', 'width=800,height=900')
  if (!w) {
    alert('Popup blocked — allow popups for this site to download PDFs.')
    return
  }
  const fmt = (s: any) =>
    typeof s === 'string' ? s : JSON.stringify(s, null, 2)

  const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>${invention.title || 'Invention'}</title>
<style>
  body { font-family: 'Poppins', system-ui, sans-serif; padding: 40px; max-width: 720px; margin: 0 auto; line-height: 1.6; color: #222; }
  h1 { font-family: 'Kanit', system-ui, sans-serif; font-size: 28px; margin: 0 0 8px; }
  h2 { font-family: 'Kanit', system-ui, sans-serif; font-size: 18px; margin-top: 32px; padding-bottom: 6px; border-bottom: 1px solid #ddd; }
  h3 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.1em; color: #666; margin-top: 18px; }
  .meta { color: #666; font-size: 12px; margin-bottom: 24px; }
  .lens { margin-bottom: 12px; }
  .lens-label { font-weight: 600; color: #444; }
  pre { background: #f6f6f6; padding: 12px; border-radius: 6px; white-space: pre-wrap; font-size: 11px; }
  ul, ol { padding-left: 20px; }
  @media print { body { padding: 20px; } }
</style></head><body>
  <h1>${invention.title || 'Invention'}</h1>
  <div class="meta">${invention.domain || ''} · seed: ${args.seedConcept}</div>

  ${mvpSpec?.oneLiner ? `<p><em>${mvpSpec.oneLiner}</em></p>` : ''}

  <h2>MVP Specification</h2>
  ${mvpSpec?.problemSolved ? `<h3>Problem solved</h3><p>${mvpSpec.problemSolved}</p>` : ''}
  ${
    mvpSpec?.components?.length
      ? `<h3>Components</h3><ul>${mvpSpec.components.map((c: string) => `<li>${c}</li>`).join('')}</ul>`
      : ''
  }
  ${
    mvpSpec?.prototypeSteps?.length
      ? `<h3>Prototype steps</h3><ol>${mvpSpec.prototypeSteps.map((s: string) => `<li>${s}</li>`).join('')}</ol>`
      : ''
  }

  <h2>Dream Agents</h2>
  ${Object.entries(agents)
    .map(([lens, output]) => `<div class="lens"><div class="lens-label">${lens}</div><div>${fmt(output)}</div></div>`)
    .join('')}

  <h2>Synthesis</h2>
  <pre>${fmt(synthesis)}</pre>

  <h2>Critique</h2>
  <pre>${fmt(critique)}</pre>

  <hr style="margin-top:40px;border:none;border-top:1px solid #ccc;" />
  <p style="font-size:11px;color:#999;">Generated by Inventor Studio · ${new Date().toLocaleString()}</p>
  <script>setTimeout(() => window.print(), 300);</script>
</body></html>`
  w.document.write(html)
  w.document.close()
}
